language: php

before_install:
  - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-en language-pack-es

php:
  - '5.5'
  - '5.6'
  - '7.0'

before_script:
  - composer self-update
  - composer install --no-interaction

script: phpunit --coverage-text